phone_number: +1 234 567 89
support_email: support@mail.com
empty_path: javascript:void(0);
sharp_path: "#"
logo_medium: 96
logo_small: 64
url:
  placeholder:
    home_image: "https://via.placeholder.com/2000X1333//88929f/5a6270C/O https://placeholder.com/"
    job: "https://via.placeholder.com/84x84"
    avatar: "https://via.placeholder.com/400X400//88929f/5a6270C/O https://placeholder.com/"
validations:
  user:
    email_regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i'
    name_minlength: 1
    name_maxlength: 50
    email_minlength: 10
    email_maxlength: 255
    password_minlength: 6
    password_maxlength: 15
    ava_size: 80
    password_reset_expired: 2
    default_password: "123456"
  job_post:
    title_min: 5
    title_max: 255
    number_min: 2
    number_max: 10
    content_min: 10
    content_max: 2000
    min: 0
    max: 2147483647
  profile:
    first_name:
      minimum: 1
      maximum: 255
    last_name:
      minimum: 1
      maximum: 255
    address:
      maximum: 255
    introduction:
      maximum: 2000
    phone_number: !ruby/regexp '/(03|07|08|09|01[2|6|8|9])+([0-9]{8})\b/'
  education:
    name:
      minimum: 1
      maximum: 255
    text:
      minimum: 0
      maximum: 2000
  experience:
    company_name:
      minimum: 5
      maximum: 255
    job_position:
      minimum: 5
      maximum: 255
    additional_information:
      maximum: 2000
user:
  checkbox_value: "1"
job_applications:
  per_page: 5
job_posts:
  per_page: 10
role:
  candidate: 1
  recruiter: 2
job: 4
category:
  home: 8
  per_page: 8
unit:
  hr: 1
status:
  reviewing: "reviewing"
  denied: "denied"
  interviewing: "interviewing"
  accepted: "accepted"
  cancel: "cancelled"
